import type { FastifyPluginAsync } from 'fastify'
import type { z } from 'zod'
import { requireInstanceAccess } from '~/auth/plugin'
import type { Env } from '~/config/env'
import {
  BlastBodySchema,
  BlastResponseSchema,
  CallParamsSchema,
  ErrorBodySchema,
  InstanceNameParams,
  TranscribeResponseSchema,
} from '~/http/openapi-schemas'
import type { InstanceManager } from '~/instances/manager'
import type { InstanceRepo } from '~/instances/repo'
import { badRequest, notFound, serviceUnavailable } from '~/lib/errors'
import type { MediaStorage } from '~/media/storage'
import type { CacheClient } from '~/redis/client'
import type { CallStore } from '~/store/calls'
import { executeAudioBlast } from '~/voip/audio-blast'
import { transcribeAudio } from '~/voip/audio-transcribe'

export type BlastRoutesDeps = {
  manager: InstanceManager
  env: Env
  instanceRepo: InstanceRepo
  mediaStorage?: MediaStorage
  cache?: CacheClient
  calls?: CallStore
}

type InstanceParams = { Params: z.infer<typeof InstanceNameParams> }
type CallParams = { Params: z.infer<typeof CallParamsSchema> }

export const blastRoutes: FastifyPluginAsync<BlastRoutesDeps> = async (app, deps) => {
  const { manager, mediaStorage, cache, env, calls } = deps

  app.post<InstanceParams & { Body: z.infer<typeof BlastBodySchema> }>(
    '/v1/instances/:name/calls/blast',
    {
      schema: {
        tags: ['Calls'],
        summary: 'Audio blast — call + play predefined audio + record response',
        description:
          'Starts an outbound VoIP call, waits for the callee to answer, ' +
          'plays a predefined WAV audio file, and optionally records the spoken response.\n\n' +
          'The audio file **must be a WAV** (PCM, any sample rate/channels — resampled to 16 kHz mono).\n\n' +
          'The HTTP request stays open until the blast completes or times out. ' +
          'For long audio files consider increasing your HTTP client timeout.\n\n' +
          '**Example**\n' +
          '```bash\n' +
          'curl -s -X POST "$BASE/v1/instances/sales-1/calls/blast" \\\n' +
          '  -H "X-Api-Key: $KEY" -H "content-type: application/json" \\\n' +
          '  -d \'{"to":"5511999999999","audioUrl":"https://example.com/message.wav",' +
          '"responseTimeoutMs":5000,"recordResponse":true}\'\n' +
          '```',
        security: [{ apiKey: [] }, { bearerAuth: [] }],
        params: InstanceNameParams,
        body: BlastBodySchema,
        response: {
          200: BlastResponseSchema,
          400: ErrorBodySchema,
          401: ErrorBodySchema,
          403: ErrorBodySchema,
          404: ErrorBodySchema,
          503: ErrorBodySchema,
        },
      },
    },
    async (request) => {
      const { name } = request.params
      requireInstanceAccess(request, name)

      const body = request.body
      if (!body.audioUrl) {
        throw badRequest('audioUrl is required')
      }

      const result = await executeAudioBlast({
        manager,
        instanceName: name,
        to: body.to,
        audioUrl: body.audioUrl,
        responseTimeoutMs: body.responseTimeoutMs ?? 5000,
        callTimeoutMs: body.callTimeoutMs ?? 30000,
        recordResponse: body.recordResponse ?? true,
        maxCaptureSeconds: env.CALL_RECORDING_MAX_SECONDS,
        mediaStorage,
        cache,
        calls,
        stt:
          body.transcribe !== false && env.STT_ENABLED && env.STT_API_URL && env.STT_API_KEY
            ? {
                enabled: true,
                apiUrl: env.STT_API_URL,
                apiKey: env.STT_API_KEY,
                model: env.STT_MODEL,
                temperature: env.STT_TEMPERATURE,
                language: body.sttLanguage ?? env.STT_LANGUAGE,
              }
            : undefined,
      })

      return result
    },
  )

  app.post<CallParams>(
    '/v1/instances/:name/calls/:callId/transcribe',
    {
      schema: {
        tags: ['Calls'],
        summary: 'Transcribe a call recording (STT via Groq / OpenAI-compatible)',
        description:
          'Sends the recorded audio (WAV) to a speech-to-text API and returns the transcription.\n\n' +
          '**Groq (recommended):** set `STT_API_URL=https://api.groq.com/openai`, model `whisper-large-v3`.\n\n' +
          'Requires `STT_ENABLED=true`, `STT_API_URL`, and `STT_API_KEY` env vars.\n\n' +
          'Call recordings are generated by the audio blast endpoint or by enabling call recording.',
        security: [{ apiKey: [] }, { bearerAuth: [] }],
        params: CallParamsSchema,
        response: {
          200: TranscribeResponseSchema,
          400: ErrorBodySchema,
          401: ErrorBodySchema,
          403: ErrorBodySchema,
          404: ErrorBodySchema,
          503: ErrorBodySchema,
        },
      },
    },
    async (request) => {
      const params = request.params
      requireInstanceAccess(request, params.name)

      if (!env.STT_ENABLED || !env.STT_API_URL || !env.STT_API_KEY) {
        throw serviceUnavailable('STT not configured — set STT_ENABLED=true, STT_API_URL, and STT_API_KEY')
      }

      if (!calls || !mediaStorage) {
        throw serviceUnavailable('call store or media storage unavailable')
      }

      const row = await calls.get(params.name, params.callId)
      if (!row) {
        throw notFound(`call ${params.callId} not found`)
      }

      if (row.recordingStatus !== 'ready' || !row.recordingStorageKey) {
        throw badRequest('no recording available for this call')
      }

      const stream = await mediaStorage.getStream(row.recordingStorageKey)
      const chunks: Buffer[] = []
      for await (const chunk of stream) {
        chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk))
      }
      const audioBytes = Buffer.concat(chunks)

      const result = await transcribeAudio({
        apiUrl: env.STT_API_URL,
        apiKey: env.STT_API_KEY,
        model: env.STT_MODEL,
        temperature: env.STT_TEMPERATURE,
        language: env.STT_LANGUAGE,
        audioBytes,
        filename: `call-${params.callId}.wav`,
      })

      return {
        text: result.text,
        language: result.language ?? null,
        durationSecs: result.durationSecs ?? null,
        callId: params.callId,
      }
    },
  )
}
