;
; Asterisk main configuration for zapo-rest SIP test environment.
;

[directories]
astetcdir => /etc/asterisk
astmoddir => /usr/lib/asterisk/modules
astvarlibdir => /var/lib/asterisk
astdbdir => /var/lib/asterisk
astkeydir => /var/lib/asterisk
astdatadir => /var/lib/asterisk
astagidir => /var/lib/asterisk/agi-bin
astspooldir => /var/spool/asterisk
astrundir => /var/run/asterisk
astlogdir => /var/log/asterisk

[options]
verbose = 3
debug = 0
maxcalls = 100
maxload = 0.9
dontwarn = yes
systemname = zapo-sip-test
languageprefix = yes
lockconfdir = no

[compat]
app_set = 1.6

[modules]
autoload = yes
